[project]
name = "code-review-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Syed Talha Ali Shah", email = "syedtalhaa1076@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastapi>=0.141.1",
    "ipykernel>=7.3.0",
    "langchain>=1.3.18",
    "langchain-cerebras>=0.8.2",
    "langchain-cohere>=0.6.0",
    "langchain-community>=0.4.2",
    "langchain-google-genai>=4.3.7",
    "langchain-groq>=1.1.3",
    "langchain-openrouter>=0.2.8",
    "langgraph>=1.2.11",
    "lxml>=6.1.2",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.3",
    "readability-lxml>=0.9",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "ruff>=0.16.5",
    "streamlit>=1.62.0",
    "tavily-python>=0.8.0",
    "trafilatura>=2.2.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
code-review-agent = "code_review_agent:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
